### ISSUE TITLE
Importing Flutter SDK Error: Expected identifier.

### ISSUE THREAD

**Issue by Briggs599** [millicast/flutter-sdk#24]
I've been tinkering around with the flutter SDK for Millicast and I'm running into an expected identifier issue when I try to import the millicastFlutterSDK:
![image](https://user-images.githubusercontent.com/48164242/173130955-a27d2983-ea1a-4ae4-b568-a45cceeb67ca.png)
![download](https://user-images.githubusercontent.com/48164242/173129937-2f7ebb28-c5f5-4ad4-a356-fcf1d0c91d63.png)

which seems to be an issue in the peer_connection.dart line 303:
![download](https://user-images.githubusercontent.com/48164242/173129974-d97274bf-5aaf-43a1-a5e0-a57472b64dbc.png)

I'm developing on Windows w/Vs Code, Flutter: 3.0.1. Let me know if this is a local issue or related to the SDK. 

Thanks,
Braden.

**Comment by nico-ramos** [comment]
Hi Braden, 
It's SDK related, the current SDK doesn't support Flutter `3.x`, we already fixed the compatibilty issues but we need to publish a new version.
We were waiting to finish another feature first and then publish the new version.
A quick fix, if you're just testing, would be using a `2.x.x` version of Flutter.

**Comment by fcancela** [comment]
Braden, with the latest release, you should be able to import our library using Flutter version 3 withous issues. Let us know if this worked for you.
