### ISSUE TITLE
The argument type 'Level' can't be assigned to the parameter type 'LogEvent'.

### ISSUE THREAD

**Issue by Briggs599** [millicast/flutter-sdk#42]
There are some compatibility issues with the SDK, Flutter 3.10, and Dart 3. Learn more via the Pub.dev SDK scorer: https://pub.dev/packages/millicast_flutter_sdk/score

**Comment by FredM7** [comment]
here is a PR i did yesterday on our fork of this
https://github.com/millicast/flutter-sdk/pull/41

**Comment by NicolasInzua** [comment]
Hello, Thank you Braden for bringing this issue to our attention and thank you Fred, for submitting your pull request. We will review it and keep you updated.

**Comment by Jerricho93** [comment]
Closing this issue, the fix has been merged to develop branch[here](https://github.com/millicast/flutter-sdk/pull/41). Fixes will go live in the next release.
