### ISSUE TITLE
H.265 support

### ISSUE THREAD

**Issue by maxmitchenko** [millicast/flutter-sdk#47]
Hi!
As I understand currently this package supports VP8, VP9, H.264, and AV1 codecs for Linux. Could you tell me please if you plan to support H.265 also?

**Comment by j12y** [comment]
Hello, thanks for reaching out. It would be great to understand a bit more about your workflow and target platforms. There are some nuances with regard to where and when H.265/HEVC is or will be supported.

If you haven't already, I suggest you reach out to our team and we can share more detail about timing and codec support for this SDK and the platform overall.

https://dolby.io/contact/
